/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { authLogin } from "../funcs/authLogin.js";
import { authSignup } from "../funcs/authSignup.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Auth extends ClientSDK {
  /**
   * Sign up
   */
  async signup(
    request: operations.SignupRequestBody,
    options?: RequestOptions,
  ): Promise<void> {
    return unwrapAsync(authSignup(
      this,
      request,
      options,
    ));
  }

  /**
   * Log in
   */
  async login(
    request: operations.LoginRequestBody,
    options?: RequestOptions,
  ): Promise<operations.LoginResponseBody> {
    return unwrapAsync(authLogin(
      this,
      request,
      options,
    ));
  }
}
