/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { libraryAdd } from "../funcs/libraryAdd.js";
import { libraryGet } from "../funcs/libraryGet.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";
import { PageIterator, unwrapResultIterator } from "../types/operations.js";

export class Library extends ClientSDK {
  /**
   * List books by user
   */
  async get(
    security: operations.GetUserLibrarySecurity,
    request: operations.GetUserLibraryRequest,
    options?: RequestOptions,
  ): Promise<
    PageIterator<operations.GetUserLibraryResponse, { offset: number }>
  > {
    return unwrapResultIterator(libraryGet(
      this,
      security,
      request,
      options,
    ));
  }

  /**
   * Add book to user library
   */
  async add(
    security: operations.AddBookToUserLibrarySecurity,
    request: operations.AddBookToUserLibraryRequest,
    options?: RequestOptions,
  ): Promise<void> {
    return unwrapAsync(libraryAdd(
      this,
      security,
      request,
      options,
    ));
  }
}
