/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { userGet } from "../funcs/userGet.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as components from "../models/components/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class User extends ClientSDK {
  /**
   * Get a user by ID
   */
  async get(
    request: operations.GetUserRequest,
    options?: RequestOptions,
  ): Promise<components.User> {
    return unwrapAsync(userGet(
      this,
      request,
      options,
    ));
  }
}
