/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type CreateBookRequestBody = {
  title: string;
  author: string;
  isbn10: string;
};

/** @internal */
export const CreateBookRequestBody$inboundSchema: z.ZodType<
  CreateBookRequestBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  title: z.string(),
  author: z.string(),
  isbn10: z.string(),
});

/** @internal */
export type CreateBookRequestBody$Outbound = {
  title: string;
  author: string;
  isbn10: string;
};

/** @internal */
export const CreateBookRequestBody$outboundSchema: z.ZodType<
  CreateBookRequestBody$Outbound,
  z.ZodTypeDef,
  CreateBookRequestBody
> = z.object({
  title: z.string(),
  author: z.string(),
  isbn10: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace CreateBookRequestBody$ {
  /** @deprecated use `CreateBookRequestBody$inboundSchema` instead. */
  export const inboundSchema = CreateBookRequestBody$inboundSchema;
  /** @deprecated use `CreateBookRequestBody$outboundSchema` instead. */
  export const outboundSchema = CreateBookRequestBody$outboundSchema;
  /** @deprecated use `CreateBookRequestBody$Outbound` instead. */
  export type Outbound = CreateBookRequestBody$Outbound;
}
