/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type DeleteBookRequest = {
  id: number;
};

/** @internal */
export const DeleteBookRequest$inboundSchema: z.ZodType<
  DeleteBookRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.number(),
});

/** @internal */
export type DeleteBookRequest$Outbound = {
  id: number;
};

/** @internal */
export const DeleteBookRequest$outboundSchema: z.ZodType<
  DeleteBookRequest$Outbound,
  z.ZodTypeDef,
  DeleteBookRequest
> = z.object({
  id: z.number(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace DeleteBookRequest$ {
  /** @deprecated use `DeleteBookRequest$inboundSchema` instead. */
  export const inboundSchema = DeleteBookRequest$inboundSchema;
  /** @deprecated use `DeleteBookRequest$outboundSchema` instead. */
  export const outboundSchema = DeleteBookRequest$outboundSchema;
  /** @deprecated use `DeleteBookRequest$Outbound` instead. */
  export type Outbound = DeleteBookRequest$Outbound;
}
