/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type GetBookRequest = {
  id: number;
};

/** @internal */
export const GetBookRequest$inboundSchema: z.ZodType<
  GetBookRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.number(),
});

/** @internal */
export type GetBookRequest$Outbound = {
  id: number;
};

/** @internal */
export const GetBookRequest$outboundSchema: z.ZodType<
  GetBookRequest$Outbound,
  z.ZodTypeDef,
  GetBookRequest
> = z.object({
  id: z.number(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetBookRequest$ {
  /** @deprecated use `GetBookRequest$inboundSchema` instead. */
  export const inboundSchema = GetBookRequest$inboundSchema;
  /** @deprecated use `GetBookRequest$outboundSchema` instead. */
  export const outboundSchema = GetBookRequest$outboundSchema;
  /** @deprecated use `GetBookRequest$Outbound` instead. */
  export type Outbound = GetBookRequest$Outbound;
}
