/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type GetUserRequest = {
  id: number;
};

/** @internal */
export const GetUserRequest$inboundSchema: z.ZodType<
  GetUserRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.number(),
});

/** @internal */
export type GetUserRequest$Outbound = {
  id: number;
};

/** @internal */
export const GetUserRequest$outboundSchema: z.ZodType<
  GetUserRequest$Outbound,
  z.ZodTypeDef,
  GetUserRequest
> = z.object({
  id: z.number(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetUserRequest$ {
  /** @deprecated use `GetUserRequest$inboundSchema` instead. */
  export const inboundSchema = GetUserRequest$inboundSchema;
  /** @deprecated use `GetUserRequest$outboundSchema` instead. */
  export const outboundSchema = GetUserRequest$outboundSchema;
  /** @deprecated use `GetUserRequest$Outbound` instead. */
  export type Outbound = GetUserRequest$Outbound;
}
